spring:
  datasource:
    # 配置当前要使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置MySQL的驱动程序类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.59.27:3306/test?useSSL=false
    username: alimysql
    password: ali123456
    # 进行数据库连接池的配置
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化提供的连接数
      initial-size: 5
      # 最大的连接数
      max-total: 200
      # 等待连接获取的最大超时时间
      max-wait-millis: 200
mybatis:
  type-aliases-package: com.example.test.entity
  mapper-locations: classpath:mapper/*.xml


